<?php

namespace Database\Seeders;

use App\Models\FacultyInsight;
use Illuminate\Database\Seeder;

/**
 * Faculty Insights content extracted from "Faculty Insights.pdf".
 *
 * - Text fields (title/role/country/content) are seeded here.
 * - Images are NOT seeded: normalized 900x990 JPGs live in
 *   database/seeders/data/faculty-insights/ and are uploaded
 *   manually via Admin → Homepage → Faculty Insights.
 * - Match key is `title` (faculty name, unique). Slug is
 *   auto-generated by EnsuresUniqueSlug.
 */
class FacultyInsightSeeder extends Seeder
{
    public function run(): void
    {
        $insights = [
            // PDF se extract karke yahan entries add hongi.
            // Format:
            // [
            //     'title'        => 'Faculty Name',
            //     'faculty_role' => 'Designation/Position',
            //     'country'      => 'Country',
            //     'content'      => 'Description...',
            //     'image'        => 'faculty-01-name.jpg', // manual upload reference
            //     'sort'         => 1,
            // ],
        ];

        foreach ($insights as $item) {
            FacultyInsight::updateOrCreate(
                ['title' => $item['title']],
                [
                    'faculty_role' => $item['faculty_role'] ?? null,
                    'country'      => $item['country'] ?? null,
                    'content'      => $item['content'] ?? null,
                    'sort_order'   => $item['sort'] ?? 0,
                    'is_active'    => true,
                    'published_at' => now(),
                ]
            );
        }

        $this->command?->info('Seeded '.count($insights).' faculty insights (images: manual upload via admin).');
    }
}
