<?php

namespace Database\Seeders;

use App\Models\FacultyInsight;
use App\Support\PublicContentCache;
use Illuminate\Database\Seeder;

/**
 * Faculty Insights content extracted from "uploads/faculty-insights.pdf".
 *
 * - Text fields (title/role/country/content/link) are seeded here.
 * - Images are NOT seeded: normalized 900x990 JPGs live in
 *   database/seeders/data/faculty-insights/ and are uploaded
 *   manually via Admin → Homepage → Faculty Insights.
 *   See README.md in that folder for the faculty → image mapping.
 * - Match key is `title` (faculty name, unique). Slug is
 *   auto-generated by EnsuresUniqueSlug.
 *
 * Normalizations applied (flagged to content owner):
 * - `country` uses country names (PDF mixed nationalities like
 *   "British", "slovakia", "Ukrainian").
 * - "Adjunct Faculty" typo in PDF fixed to "Adjunct Faculty".
 * - Subject-expertise lines (entries 1-4) folded into the start of
 *   `content` since the card has a single role line.
 * - LinkedIn URLs stored in `link_url` (not rendered yet, kept for
 *   future use); tracking params stripped.
 */
class FacultyInsightSeeder extends Seeder
{
    public function run(): void
    {
        $insights = [
            [
                'title' => 'Prof. Dr. David Mark Holliman',
                'faculty_role' => 'Associate Faculty',
                'country' => 'United Kingdom',
                'content' => 'Global Leadership, Design Thinking, Counselling Psychology, Education and Management Curriculum Development. Dr. David Holliman, an educator with 15+ years of experience, is Chairman of Holliman Holdings, managing business operations in tourism, trading, asset management, and education.',
                'link_url' => 'https://www.linkedin.com/in/drdavid-holliman',
                'image' => 'faculty-01-david-holliman.jpg',
                'sort' => 1,
            ],
            [
                'title' => 'Prof. Dr. Othman Abu Khurma',
                'faculty_role' => 'Adjunct Faculty',
                'country' => 'Jordan',
                'content' => 'Quality Assurance of Assessment Process & Practices (IQA). Dr. Othman Abu Khurma, a passionate science educator with 18 years\' experience in Jordan and the GCC, excels in designing engaging teaching materials, fostering dynamic discussions, enhancing learning for educators and students.',
                'link_url' => 'https://www.linkedin.com/in/dr-othman-abu-khurma-38221432',
                'image' => 'faculty-02-othman-abu-khurma.jpg',
                'sort' => 2,
            ],
            [
                'title' => 'Prof. Steve Alban Tineo',
                'faculty_role' => 'Adjunct Faculty',
                'country' => 'Switzerland',
                'content' => 'Strategy Leadership & Emotional Intelligence. Prof. Steve, a global leader and entrepreneur with 20+ years of experience, delivers corporate training and academic courses on negotiation, conflict resolution, mediation, and cross-cultural communication.',
                'link_url' => 'https://www.linkedin.com/in/stevealbantineo',
                'image' => 'faculty-03-steve-alban-tineo.jpg',
                'sort' => 3,
            ],
            [
                'title' => 'Prof. Alexander Schmidt',
                'faculty_role' => 'Adjunct Faculty',
                'country' => 'Germany',
                'content' => 'Artificial Intelligence & Data Science. Alexander is a leader in AI and cloud integration, specializing in ethical AI strategy and financial services. He develops courses on Machine Learning, NLP, and AI ethics, driving tech business growth.',
                'link_url' => 'https://www.linkedin.com/in/alexanderschmidt',
                'image' => 'faculty-04-alexander-schmidt.jpg',
                'sort' => 4,
            ],
            [
                'title' => 'Prof. Veronika Knight',
                'faculty_role' => 'Human-Centered Soft Skills Trainer & Women\'s Empowerment Ambassador',
                'country' => 'Slovakia',
                'content' => 'Veronika Knight delivers practical, human-centered learning experiences for corporate teams across the UAE and GCC. Her approach focuses on developing soft skills and encouraging meaningful behavioural change, helping learners apply their knowledge with confidence in the workplace.',
                'link_url' => 'https://www.linkedin.com/in/veronikaknight',
                'image' => 'faculty-05-veronika-knight.jpg',
                'sort' => 5,
            ],
            [
                'title' => 'Shyma Mohaisen',
                'faculty_role' => 'Corporate Trainer & Business Instructor',
                'country' => 'Canada',
                'content' => 'Shyma brings over 10 years of teaching experience and a background at Microsoft, combining academic expertise with practical industry insights to support learners\' professional growth.',
                'link_url' => 'https://www.linkedin.com/in/shymamohaisen',
                'image' => 'faculty-06-shyma-mohaisen.jpg',
                'sort' => 6,
            ],
            [
                'title' => 'Prof. Dr. Shanmugan Joghee',
                'faculty_role' => 'Professor & Discipline Leader – Marketing',
                'country' => 'India',
                'content' => 'Dr. Shanmugan brings over 26 years of experience in management education and research across India and the UAE, with expertise in marketing, international business, research methods, and digital transformation.',
                'link_url' => 'https://www.linkedin.com/in/prof-dr-shanmugan-joghee-058b2247',
                'image' => 'faculty-07-shanmugan-joghee.jpg',
                'sort' => 7,
            ],
            [
                'title' => 'Prof. Yana Nikitina',
                'faculty_role' => 'Economist, Educator & Researcher',
                'country' => 'Ukraine',
                'content' => 'Prof. Yana Nikitina is an accomplished economist, lecturer, and researcher with a PhD in Economics and a Master\'s in Education Leadership. She brings extensive experience in teaching Economics, Finance, Accounting, and Business, with a strong commitment to student-centred learning, research excellence, and professional development.',
                'link_url' => 'https://www.linkedin.com/in/yana-nikitina-125b612a',
                'image' => 'faculty-08-yana-nikitina.jpg',
                'sort' => 8,
            ],
        ];

        foreach ($insights as $item) {
            FacultyInsight::updateOrCreate(
                ['title' => $item['title']],
                [
                    'faculty_role' => $item['faculty_role'] ?? null,
                    'country' => $item['country'] ?? null,
                    'content' => $item['content'] ?? null,
                    'link_url' => $item['link_url'] ?? null,
                    'sort_order' => $item['sort'] ?? 0,
                    'is_active' => true,
                    'published_at' => now(),
                ]
            );
        }

        // Full db:seed runs with WithoutModelEvents, so the saved-hooks
        // won't flush — clear the public cache explicitly.
        PublicContentCache::flush();

        $this->command?->info('Seeded '.count($insights).' faculty insights (images: manual upload via admin).');
    }
}
