{{-- Image Slideshow Section for Our Story — Stylish/fancy slideshow with categories --}}
@if(($galleryImages ?? collect())->count() > 0)
<section id="gallery" class="os-slideshow" aria-label="Image Slideshow">
  <div class="container">
    <div class="os-slideshow__header">
      <span class="os-section-label fade-up">Moments</span>
      <h2 class="os-section-heading os-section-heading--center fade-up">
        Moments That <em>Define Us</em>
      </h2>
      <p class="os-body-text os-body-text--center fade-up">
        A visual journey through our milestones, collaborations, and celebrations.
      </p>
    </div>

    {{-- Category Filters --}}
    @php
      $galleryCategories = $galleryImages->pluck('category')->filter()->unique()->values();
    @endphp
    @if($galleryCategories->count() > 0)
    <div class="os-slideshow__filters fade-up">
      <button class="os-slideshow__filter os-slideshow__filter--active" data-filter="all">All</button>
      @foreach($galleryCategories as $category)
        <button class="os-slideshow__filter" data-filter="{{ Str::slug($category) }}">{{ $category }}</button>
      @endforeach
    </div>
    @endif

    {{-- Slideshow Carousel --}}
    <div class="os-slideshow__carousel" data-slideshow>
      <div class="os-slideshow__track" data-slideshow-track>
        @foreach($galleryImages as $idx => $img)
        <div class="os-slideshow__slide" data-category="{{ $img->category ? Str::slug($img->category) : 'all' }}">
          <div class="os-slideshow__slide-inner">
            <img
              src="{{ $img->image_url }}"
              alt="{{ $img->caption ?? 'Maverick Business Academy' }}"
              class="os-slideshow__img"
              loading="lazy"
            />
            @if($img->caption || $img->category)
            <div class="os-slideshow__caption">
              @if($img->caption)
              <span class="os-slideshow__caption-text">{{ $img->caption }}</span>
              @endif
              @if($img->category)
              <span class="os-slideshow__caption-cat">{{ $img->category }}</span>
              @endif
            </div>
            @endif
          </div>
        </div>
        @endforeach
      </div>
    </div>

    {{-- Slideshow Controls --}}
    <div class="os-slideshow__controls">
      <button class="os-slideshow__btn os-slideshow__btn--prev" data-slideshow-prev aria-label="Previous">
        <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
      </button>
      <div class="os-slideshow__dots" data-slideshow-dots>
        {{-- Dots generated by JS --}}
      </div>
      <button class="os-slideshow__btn os-slideshow__btn--next" data-slideshow-next aria-label="Next">
        <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
      </button>
    </div>
  </div>

  {{-- Lightbox --}}
  <div class="os-lightbox" id="os-lightbox" aria-hidden="true">
    <button class="os-lightbox__close" data-lightbox-close aria-label="Close lightbox">
      <span data-lucide="x"></span>
    </button>
    <button class="os-lightbox__prev" data-lightbox-prev aria-label="Previous image">
      <span data-lucide="chevron-left"></span>
    </button>
    <button class="os-lightbox__next" data-lightbox-next aria-label="Next image">
      <span data-lucide="chevron-right"></span>
    </button>
    <div class="os-lightbox__content">
      <img class="os-lightbox__img" id="os-lightbox-img" src="" alt="" />
      <p class="os-lightbox__caption" id="os-lightbox-caption"></p>
    </div>
  </div>
</section>
@endif
